AdminLTE/AdminLTE/Models/LogEntry.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AdminLTE.Models
{
    public class LogEntry
    {
        public Int64 LogEntryID { get; set; }

        [Required]
        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime LogDate { get; set; }

        [Required]
        [MaxLength(30, ErrorMessage = "Máximo {0} caracteres")]
        public string Logger { get; set; }

        [Required]
        [Display(Name = "Level")]
        [MaxLength(5, ErrorMessage = "Máximo {0} caracteres")]
        public string LogLevel { get; set; }

        [Required]
        [MaxLength(10, ErrorMessage = "Máximo {0} caracteres")]
        public string Thread { get; set; }

        [Display(Name = "Entity")]
        [Required]
        [MaxLength(50, ErrorMessage = "Máximo {0} caracteres")]
        [Index("IDX_LogEntries_Entity", Order = 2)]
        public string EntityFormalNamePlural { get; set; }

        [Display(Name = "Key")]
        [Required]
        [Index("IDX_LogEntries_Entity", Order = 1)]
        public int EntityKeyValue { get; set; }

        [Display(Name = "Usuario")]
        [MaxLength(256, ErrorMessage = "Máximo {0} caracteres")]
        public string UserName { get; set; }

        [MaxLength(256, ErrorMessage = "Máximo {0} caracteres")]
        public string Message { get; set; }

        public string Exception { get; set; }
    }
}

AdminLTE/AdminLTE/Controllers/LogEntriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdminLTE.Models;
using PagedList;

namespace AdminLTE.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LogEntriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: LogEntries
        public ActionResult Index(String sort, string search, int? page)
        {
            ViewBag.LogLevelSort = String.IsNullOrEmpty(sort) ? "LogLevel_desc" : string.Empty;
            ViewBag.LogDateSort = sort == "LogDate" ? "LogDate_desc" : "LogDate";
            ViewBag.EntityFormalNamePluralSort = sort == "EntityFormalNamePlural" ? "EntityFormalNamePlural_desc" : "EntityFormalNamePlural";
            ViewBag.UserNameSort = sort == "UserName" ? "UserName_desc" : "UserName";
            ViewBag.MessageSort = sort == "Message" ? "Message_desc" : "Message";
            ViewBag.ExceptionSort = sort == "Exception" ? "Exception_desc" : "Exception";

            ViewBag.CurrentSort = sort;
            ViewBag.CurrentSearch = search;

            IQueryable<LogEntry> logEntries = db.LogEntries.OrderByDescending(le => le.LogEntryID);

            if (!string.IsNullOrEmpty(search)) logEntries = logEntries.Where(ii => ii.LogLevel.Contains(search) || ii.EntityFormalNamePlural.Contains(search) || ii.UserName.Contains(search) || ii.Message.Contains(search) || ii.Exception.Contains(search));

            switch (sort)
            {
                case "LogLevel_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.LogLevel);
                    break;

                case "LogDate":
                    logEntries = logEntries.OrderBy(ii => ii.LogDate);
                    break;

                case "LogDate_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.LogDate);
                    break;

                case "EntityFormalNamePlural":
                    logEntries = logEntries.OrderBy(ii => ii.EntityFormalNamePlural);
                    break;

                case "EntityFormalNamePlural_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.EntityFormalNamePlural);
                    break;

                case "UserName":
                    logEntries = logEntries.OrderBy(ii => ii.UserName);
                    break;

                case "UserName_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.UserName);
                    break;

                case "Message":
                    logEntries = logEntries.OrderBy(ii => ii.Message);
                    break;

                case "Message_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.Message);
                    break;

                case "Exception":
                    logEntries = logEntries.OrderBy(ii => ii.Exception);
                    break;

                case "Exception_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.Exception);
                    break;

                default:
                    logEntries = logEntries.OrderBy(ii => ii.LogLevel);
                    break;

            }



            int pageSize = 5;
            int pageNumber = page ?? 1;

            //return View(logEntries.ToPagedList(pageNumber, pageSize));

            return View(logEntries.ToPagedList(pageNumber, pageSize));
        }

        //Index para usuario
        public ActionResult IndexUser(String sort, string search, int? page)
        {
            ViewBag.LogLevelSort = String.IsNullOrEmpty(sort) ? "LogLevel_desc" : string.Empty;
            ViewBag.LogDateSort = sort == "LogDate" ? "LogDate_desc" : "LogDate";
            ViewBag.EntityFormalNamePluralSort = sort == "EntityFormalNamePlural" ? "EntityFormalNamePlural_desc" : "EntityFormalNamePlural";
            ViewBag.UserNameSort = sort == "UserName" ? "UserName_desc" : "UserName";
            ViewBag.MessageSort = sort == "Message" ? "Message_desc" : "Message";
            
            ViewBag.CurrentSort = sort;
            ViewBag.CurrentSearch = search;

            IQueryable<LogEntry> logEntries = db.LogEntries.OrderByDescending(le => le.LogEntryID);

            if (!string.IsNullOrEmpty(search)) logEntries = logEntries.Where(ii => ii.LogLevel.Contains(search) || ii.EntityFormalNamePlural.Contains(search) || ii.UserName.Contains(search) || ii.Message.Contains(search));

            switch (sort)
            {
                case "LogLevel_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.LogLevel);
                    break;

                case "LogDate":
                    logEntries = logEntries.OrderBy(ii => ii.LogDate);
                    break;

                case "LogDate_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.LogDate);
                    break;

                case "EntityFormalNamePlural":
                    logEntries = logEntries.OrderBy(ii => ii.EntityFormalNamePlural);
                    break;

                case "EntityFormalNamePlural_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.EntityFormalNamePlural);
                    break;

                case "UserName":
                    logEntries = logEntries.OrderBy(ii => ii.UserName);
                    break;

                case "UserName_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.UserName);
                    break;

                case "Message":
                    logEntries = logEntries.OrderBy(ii => ii.Message);
                    break;

                case "Message_desc":
                    logEntries = logEntries.OrderByDescending(ii => ii.Message);
                    break;

                default:
                    logEntries = logEntries.OrderBy(ii => ii.LogLevel);
                    break;

            }



            int pageSize = 5;
            int pageNumber = page ?? 1;

            return View(logEntries.ToPagedList(pageNumber, pageSize));
        }

        // GET: LogEntries/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LogEntry logEntry = db.LogEntries.Find(id);
            if (logEntry == null)
            {
                return HttpNotFound();
            }
            return View(logEntry);
        }

        // GET: LogEntries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LogEntries/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LogEntryID,LogDate,Logger,LogLevel,Thread,EntityFormalNamePlural,EntityKeyValue,UserName,Message,Exception")] LogEntry logEntry)
        {
            if (ModelState.IsValid)
            {
                db.LogEntries.Add(logEntry);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(logEntry);
        }

        // GET: LogEntries/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LogEntry logEntry = db.LogEntries.Find(id);
            if (logEntry == null)
            {
                return HttpNotFound();
            }
            return View(logEntry);
        }

        // POST: LogEntries/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LogEntryID,LogDate,Logger,LogLevel,Thread,EntityFormalNamePlural,EntityKeyValue,UserName,Message,Exception")] LogEntry logEntry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(logEntry).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(logEntry);
        }

        // GET: LogEntries/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LogEntry logEntry = db.LogEntries.Find(id);
            if (logEntry == null)
            {
                return HttpNotFound();
            }
            return View(logEntry);
        }

        // POST: LogEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            LogEntry logEntry = db.LogEntries.Find(id);
            db.LogEntries.Remove(logEntry);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdminLTE/AdminLTE/Views/LogEntries/Create.cshtml
@model AdminLTE.Models.LogEntry

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LogEntry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LogDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logger, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logger, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logger, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LogLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LogLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thread, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thread, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thread, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntityFormalNamePlural, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntityFormalNamePlural, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntityFormalNamePlural, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntityKeyValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntityKeyValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntityKeyValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Exception, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Exception, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Exception, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdminLTE/AdminLTE/Views/LogEntries/Delete.cshtml
@model AdminLTE.Models.LogEntry

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LogEntry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LogLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thread)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thread)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntityFormalNamePlural)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntityFormalNamePlural)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntityKeyValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntityKeyValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exception)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exception)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdminLTE/AdminLTE/Views/LogEntries/Index.cshtml
@*@model IEnumerable<AdminLTE.Models.LogEntry>*@
           
@using PagedList.Mvc
@model PagedList.IPagedList<AdminLTE.Models.LogEntry>




@{
    ViewBag.Title = "Pistas de auditoria";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            <div class="box-header">
                <h2>@ViewBag.Title</h2>

                <p>
                    @*@Html.ActionLink("Create New", "Create")*@
                </p>
            </div>
            <div class="box-body">
                
                <div class="input-group">

                    @using (Html.BeginForm("Index", "LogEntries", FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <div class="input-group">
                            @Html.TextBox("search", ViewBag.CurrentSearch as string, new { @class = "form-control", placeholder = "Escriba la Busqueda", aria_describedby = "basic-addon2" })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">Buscar</button>
                            </span>
                        </div><!-- /input-group -->
                    }

                </div>

                    <table class="table">
                        <tr class="info">
                            <th>
                                @*@Html.DisplayNameFor(model => model.LogDate)*@
                                @Html.ActionLink("LogDate", "Index", new { sort = ViewBag.LogDateSort, search = ViewBag.CurrentSearch })
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.Logger)*@
                                @*@Html.ActionLink("Logger", "#")*@
                                @Html.Raw("Logger")
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.LogLevel)*@
                                @Html.ActionLink("LogLevel", "Index", new { sort = ViewBag.LogLevelSort, search = ViewBag.CurrentSearch })
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.Thread)*@
                                @*@Html.ActionLink("Thread", "#")*@
                                @Html.Raw("Thread")
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.EntityFormalNamePlural)*@
                                @Html.ActionLink("EntityFormalNamePlural", "Index", new { sort = ViewBag.EntityFormalNamePluralSort, search = ViewBag.CurrentSearch })
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.EntityKeyValue)*@
                                @*@Html.ActionLink("EntityKeyValue", "#")*@
                                @Html.Raw("EntityKeyValue")
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.UserName)*@
                                @Html.ActionLink("UserName", "Index", new { sort = ViewBag.UserNameSort, search = ViewBag.CurrentSearch })
                            </th>
                            <th>
                                @*@Html.DisplayNameFor(model => model.Message)*@
                                @Html.ActionLink("Message", "Index", new { sort = ViewBag.MessageSort, search = ViewBag.CurrentSearch })
                            </th>
                            @*<th>
                                @Html.ActionLink("Exception", "Index", new { sort = ViewBag.ExceptionSort, search = ViewBag.CurrentSearch })
                            </th>*@
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LogDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Logger)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LogLevel)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Thread)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EntityFormalNamePlural)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EntityKeyValue)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Message)
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.Exception)
                                </td>*@
                                <td>
                                    @*@Html.ActionLink("Edit", "Edit", new { id = item.LogEntryID }, new{@class = "btn btn-primary btn-xs"})*@
                                    @Html.ActionLink("Details", "Details", new { id = item.LogEntryID }, new {@class = "btn btn-info btn-xs"})
                                    @*@Html.ActionLink("Delete", "Delete", new { id = item.LogEntryID }, new{ @class = "btn btn-danger btn-xs"})*@
                                </td>
                            </tr>
                        }

                    </table>

                
                Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index", new { sort = ViewBag.CurrentSort, search = ViewBag.CurrentSearch, page }))
            </div>
        </div>
    </div>
</div>

AdminLTE/AdminLTE/Views/LogEntries/IndexUser.cshtml
@*@model IEnumerable<AdminLTE.Models.LogEntry>*@

@using PagedList.Mvc
@model PagedList.IPagedList<AdminLTE.Models.LogEntry>




@{
    ViewBag.Title = "Pistas de auditoria";
}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="box box-info">
            <div class="box-header">
                <h2>@ViewBag.Title</h2>

                <p>
                    @*@Html.ActionLink("Create New", "Create")*@
                </p>
            </div>
            <div class="box-body">

                <div class="input-group">

                    @using (Html.BeginForm("IndexUser", "LogEntries", FormMethod.Get, new { @class = "form-inline" }))
                    {
                        <div class="input-group">
                            @Html.TextBox("search", ViewBag.CurrentSearch as string, new { @class = "form-control", placeholder = "Escriba la Busqueda", aria_describedby = "basic-addon2" })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">Buscar</button>
                            </span>
                        </div><!-- /input-group -->
                    }

                </div>

                <table class="table">
                    <tr class="info">
                        <th>
                            @Html.ActionLink("LogDate", "IndexUser", new { sort = ViewBag.LogDateSort, search = ViewBag.CurrentSearch })
                        </th>
                        <th>
                            @Html.ActionLink("LogLevel", "IndexUser", new { sort = ViewBag.LogLevelSort, search = ViewBag.CurrentSearch })
                        </th>
                        <th>
                            @Html.ActionLink("EntityFormalNamePlural", "IndexUser", new { sort = ViewBag.EntityFormalNamePluralSort, search = ViewBag.CurrentSearch })
                        </th>
                        <th>
                            @Html.ActionLink("UserName", "IndexUser", new { sort = ViewBag.UserNameSort, search = ViewBag.CurrentSearch })
                        </th>
                        <th>
                            @Html.ActionLink("Message", "IndexUser", new { sort = ViewBag.MessageSort, search = ViewBag.CurrentSearch })
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.LogDate)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Logger)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.LogLevel)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Thread)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.EntityFormalNamePlural)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.EntityKeyValue)
                            </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Message)
                            </td>
                            @*<td>
                                @Html.DisplayFor(modelItem => item.Exception)
                            </td>*@
                            <td>
                                @*@Html.ActionLink("Edit", "Edit", new { id = item.LogEntryID }, new { @class = "btn btn-primary btn-xs" })*@
                            </td>
                        </tr>
                    }

                </table>


                Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("IndexUser", new { sort = ViewBag.CurrentSort, search = ViewBag.CurrentSearch, page }))
            </div>
        </div>
    </div>
</div>




@*@{
    ViewBag.Title = "IndexUser";
}

<h2>IndexUser</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LogDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logger)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Thread)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EntityFormalNamePlural)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EntityKeyValue)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exception)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LogDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Logger)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LogLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Thread)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntityFormalNamePlural)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntityKeyValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exception)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LogEntryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LogEntryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LogEntryID })
        </td>
    </tr>
}

</table>*@