AdminLTE/AdminLTE/Models/checkDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AdminLTE.Models
{
    [Table("checkdetail", Schema = "adm")]
    public class checkDetail
    {
        public checkDetail()
        {
            uniquefield = Guid.NewGuid().ToString();
            active = true;
        }

        [Key]
        public int id { get; set; }

        [Index("INDEX_ADM_CHECKDETAIL", 1, IsUnique = true)]
        public int checkId { get; set; }

        [Index("INDEX_ADM_CHECKDETAIL", 2, IsUnique = true)]
        [MaxLength(128, ErrorMessage = "Máximo {0} caracteres")]
        [RegularExpression(@"^[a-zA-Z0-9 '' ']+$", ErrorMessage = "No se permiten caracteres especiales")]
        [Display(Name = "Descripción")]
        [Required]
        public string name { get; set; }

        [RegularExpression(@"^[0-9\.]+$", ErrorMessage = "Solo se permite numeros")]
        [Display(Name = "Monto")]
        [Required]
        public decimal amount { get; set; }





        //Campos de control
        [Index("INDEX_ADM_CHECKDETAIL_UNIQUEFIELD", IsUnique = true)]
        [ScaffoldColumn(false)]
        [Display(Name = "Campo unico")]
        [MaxLength(128, ErrorMessage = "Máximo {0} caracteres")]
        [Required]
        public string uniquefield { get; set; }

        [Display(Name = "Activo")]
        [Required]
        public bool active { get; set; }

        [ScaffoldColumn(false)]
        [Timestamp]
        public byte[] fieldControl { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.Date)]
        [Required]
        public DateTime dateCreation { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.Date)]
        [Required]
        public DateTime dateModification { get; set; }





        //Relaciones
        public virtual check checks { get; set; }
    }
}

AdminLTE/AdminLTE/Controllers/checkDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using AdminLTE.Models;
using PagedList;

namespace AdminLTE.Controllers
{
    public class checkDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: checkDetails
        public ActionResult Index(int checkId, string search, int? page, string sort)
        {
            check check = db.checks.FirstOrDefault(c => c.id == checkId);
            ViewBag.checkUF = check.uniquefield;
            ViewBag.CurrentSearch = search;
            ViewBag.page = page;

            ViewBag.checkId = checkId;
            var checkDetails = db.checkDetails.Include(c => c.checks).Where(cs => cs.checkId == checkId);

            if (!string.IsNullOrEmpty(search)) checkDetails = checkDetails.Where(cd => cd.name.Contains(search));

            ViewBag.descriptionSort = sort == "description" ? "description_desc" : "description";
            ViewBag.amountSort = sort == "amount" ? "amount_desc" : "amount";
            ViewBag.activeSort = sort == "active" ? "active_desc" : "active";

            ViewBag.CurrentSort = sort;

            switch (sort)
            {
                case "description_desc":
                    checkDetails = checkDetails.OrderByDescending(cd => cd.name);
                    break;

                case "amount":
                    checkDetails = checkDetails.OrderBy(cd => cd.amount);
                    break;

                case "amount_desc":
                    checkDetails = checkDetails.OrderByDescending(cd => cd.amount);
                    break;

                case "active":
                    checkDetails = checkDetails.OrderBy(cd => cd.active);
                    break;

                case "active_desc":
                    checkDetails = checkDetails.OrderByDescending(cd => cd.active);
                    break;

                default:
                    checkDetails = checkDetails.OrderBy(cd => cd.name);
                    break;

            }

            int pageSize = 3;
            int pageNumber = page ?? 1;

            //return View(sales.ToPagedList(pageNumber, pageSize));

            return PartialView("_Index", checkDetails.ToPagedList(pageNumber, pageSize));
        }

        // GET: checkDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            checkDetail checkDetail = db.checkDetails.Find(id);
            if (checkDetail == null)
            {
                return HttpNotFound();
            }

            return View(checkDetail);
        }

        // GET: checkDetails/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            //ViewBag.checkId = new SelectList(db.checks, "id", "checkNumber");
            return PartialView("_Create");
        }

        // POST: checkDetails/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,checkId,name,amount,uniquefield,active,fieldControl,dateCreation,dateModification")] checkDetail checkDetail)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.checkDetails.Add(checkDetail);
                    
                    check check = db.checks.Find(checkDetail.checkId);
                    decimal registeredAmounts = amountsOfMovements(checkDetail.checkId);
                    decimal available = check.amount - registeredAmounts;

                    //Consulta para comprobar si el cheque tiene firmas
                    var availableSignatures = (from dosbc in db.detailOfSignaturesByChecks.Where(dosbc => dosbc.checkId == checkDetail.checkId)
                                               select dosbc);

                    if (availableSignatures.Any())
                    {
                        if (checkDetail.amount <= available)
                        {
                            db.SaveChanges();
                            Log4NetHelper.Log(String.Format("Movimiento de cheque con ID: {0}, para el cheque con ID: {1} Creado!", checkDetail.id, checkDetail.checkId), LogLevel.INFO, "checkDetail", checkDetail.id, User.Identity.Name, null);
                            return RedirectToAction("Edit", "checks", new { uniquefield = check.uniquefield });
                        }
                        else
                        {
                            TempData["msgErrorMovement"] = String.Format("El monto excede al disponible");
                            //return new ContentResult();
                        }
                    }
                    else
                    {
                        TempData["msgErrorMovement"] = String.Format("Primero debe agregar una firma");
                        //return new ContentResult();
                    }
                }
                catch (Exception ex)
                {
                    var e = ex.GetBaseException() as SqlException;
                    Log4NetHelper.Log(String.Format("Error al crear un movimiento de cheque"), LogLevel.ERROR, "CheckDetail", 0, User.Identity.Name, ex);
                    if (e != null)
                        switch (e.Number)
                        {
                            case 2601:
                                TempData["msgErrorMovement"] = String.Format("Error al guardar movimientos duplicados");
                                return new ContentResult();
                                break;
                            default:
                                TempData["msgErrorMovement"] = String.Format(e.Message);
                                return new ContentResult();
                        }
                }
            }
            else
            {
                if (checkDetail.name == null || checkDetail.amount == 0)
                {
                    TempData["msgErrorMovement"] = String.Format("Ninguno de los campos puede ser nulos");
                    //return new ContentResult();
                }
                else
                {
                    TempData["msgErrorMovement"] = String.Format("No se permite caracteres especiales, ni montos en negativo.");
                    //return new ContentResult();
                }
            }

            return new ContentResult();
        }

        // GET: checkDetails/Edit/5
        public ActionResult Edit(int? id, string search, int? page, string sort)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            checkDetail checkDetail = db.checkDetails.Find(id);
            check checkNumber = db.checks.Find(checkDetail.checkId);
            if (checkDetail == null)
            {
                return HttpNotFound();
            }

            ViewBag.checkNumber = checkNumber.checkNumber;
            ViewBag.checkId = checkDetail.checkId;
            ViewBag.isActive = checkDetail.active;
            ViewBag.currentAmount = checkDetail.amount;

            ViewBag.CurrentSearch = search;
            ViewBag.page = page;
            ViewBag.sort = sort;

            return PartialView("_Edit", checkDetail);
            //return RedirectToAction("Edit/" + checkDetail.checkId, "checks");
        }

        // POST: checkDetails/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,checkId,name,amount,uniquefield,active,fieldControl,dateCreation,dateModification")] checkDetail checkDetail)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(checkDetail).State = EntityState.Modified;

                    //Calculo para disponibilidad de montos
                    check check = db.checks.Find(checkDetail.checkId);
                    decimal registeredAmounts = amountsOfMovements(checkDetail.checkId);
                    decimal available = check.amount - registeredAmounts;

                    // si el monto no excede al disponible permite la edicion
                    if (checkDetail.amount <= available)
                    {
                        db.SaveChanges();
                        Log4NetHelper.Log(
                            String.Format("Movimiento de cheque con ID: {0}, para el cheque con ID: {1} Modificado!",
                                checkDetail.id, checkDetail.checkId), LogLevel.INFO, "checkDetail", checkDetail.id,
                            User.Identity.Name, null);
                        return RedirectToAction("Edit", "checks", new {uniquefield = check.uniquefield});
                    }
                    else
                    {
                        TempData["msgErrorMovement"] = String.Format("El monto excede al disponible");
                        return new ContentResult();
                    }

                }
                catch (Exception ex)
                {
                    var e = ex.GetBaseException() as SqlException;
                    Log4NetHelper.Log(String.Format("Error al editar un movimiento de cheque"), LogLevel.ERROR,

AdminLTE/AdminLTE/Views/checkDetails/Details.cshtml
@model AdminLTE.Models.checkDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>checkDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.checks.checkNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.checks.checkNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.id }) |*@
    @Html.ActionLink("Back to List", "Edit/" + Model.checks.id,"checks")
</p>

AdminLTE/AdminLTE/Views/checkDetails/_Create.cshtml
@using AdminLTE.Models
@model AdminLTE.Models.checkDetail

@*<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Añadir Movimientos</h4>
</div>
<div class="modal-body">*@
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "createDetailByCheck" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @*<h4><p class="text-danger" id="MessageToClient"></p></h4>*@
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.dateCreation, new { @Value = @DateTime.Now.ToShortDateString() })
            @Html.HiddenFor(model => model.dateModification, new { @Value = @DateTime.Now.ToShortDateString() })
            <input type="hidden" value="" name="checkId" />

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.checkId, "checkId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("checkId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.checkId, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
                </div>
                
                <div class="col-md-1">
                    <a id="btnAddDetails" class="btn btn-success">Añadir</a>
                    
                </div>
                <div class="col-md-1">
                    <a class="btn btn-default closeAddPartial" concat="Movement">Cancelar</a>
                </div>

                
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.active, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.active)
                            @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>*@

            @*<div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>*@
        </div>
    }

@*</div>
<div class="modal-footer">
    <a id="btnAddDetails" class="btn btn-success">Añadir</a>
    <a class="closeModalAdd btn btn-success">Cerrar</a>
</div>*@

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AdminLTE/AdminLTE/Views/checkDetails/_Delete.cshtml
@model AdminLTE.Models.checkDetail


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Borrar Registro</h4>
</div>
<div class="modal-body">

    <h3>¿Estás seguro que quieres borrar esto?</h3>
    <div>
        <h4>checkDetail</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.checks.checkNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.checks.checkNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.amount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.amount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.active)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.active)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @*@Html.ActionLink("Back to List", "Index")*@
            </div>
        }
    </div>
</div>
<div class="modal-footer">
    @*<a class="close btn btn-primary" href="/checks/Edit/@Html.Raw(ViewBag.checkUF)">Regresar</a>*@
    <button type="button" class="close btn-default" data-dismiss="modal">cerrar</button>
</div>

AdminLTE/AdminLTE/Views/checkDetails/_Edit.cshtml
@model AdminLTE.Models.checkDetail

@{
    ViewBag.Title = "Edit";
}

<td>
    @*<input type="text" value="@Html.Raw(ViewBag.checkNumber)" disabled />*@
</td>

<td>
    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "" } })
    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
</td>

<td>
    @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "" } })
    @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
</td>
<td>
    @Html.EditorFor(model => model.active)
    @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
</td>

<td>

    @using (Html.BeginForm(null, null, FormMethod.Post, new {id = "editCheckDetailsForm"}))
    {

        @Html.AntiForgeryToken()
        @*<div class="form-inline">*@

        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.dateCreation)
        @Html.HiddenFor(model => model.dateModification, new {@Value = @DateTime.Now.ToShortDateString()})
        @Html.HiddenFor(model => model.fieldControl)
        @Html.HiddenFor(model => model.uniquefield)
        <input type="hidden" value="@Html.Raw(ViewBag.checkId)" name="checkId" />

        
        <input type="hidden" value="" name="name"/>
        <input type="hidden" value="" name="amount" />
        <input type="hidden" value="" name="active" />
        
        <a id="movementsSave" class="btnSave btn btn-success btn-xs" type-id="movements">Guardar</a>
        <a class="refreshPartialMov btn btn-default btn-xs" href="/checkDetails/Index?checkId=@Html.Raw(ViewBag.checkId + "&search=" + ViewBag.CurrentSearch + "&page=" + ViewBag.page + "&sort=" + ViewBag.sort)">cancel</a>
        
    } 

</td>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AdminLTE/AdminLTE/Views/checkDetails/_Index.cshtml
@using System.Activities.Statements
@*@model IEnumerable<AdminLTE.Models.checkDetail>*@
           
@using AdminLTE.Models
@using PagedList.Mvc
@model PagedList.IPagedList<AdminLTE.Models.checkDetail>

<p>
    @*@Html.ActionLink("Agregar", "Create")*@
    
</p>


<table class="table" id="tableCheckDetail" onload="inactive()">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.checks.checkNumber)*@
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.name)*@
                @*@Html.ActionLink("Descripción", "Edit","checks", new { uniquefield = ViewBag.checkUF, search = ViewBag.CurrentSearch, sort = ViewBag.descriptionSort },null)*@
                <a class="refreshPartialMov" href="/checkDetails/Index?checkId=@Html.Raw(ViewBag.checkId + "&search=" + ViewBag.CurrentSearch + "&page=" + ViewBag.page + "&sort=" + ViewBag.descriptionSort)">Descripción</a>
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.amount)*@
                @*@Html.ActionLink("Monto", "Edit", "checks", new { uniquefield = ViewBag.checkUF, search = ViewBag.CurrentSearch, sort = ViewBag.amountSort }, null)*@
                <a class="refreshPartialMov" href="/checkDetails/Index?checkId=@Html.Raw(ViewBag.checkId + "&search=" + ViewBag.CurrentSearch + "&page=" + ViewBag.page + "&sort=" + ViewBag.amountSort)">Monto</a>
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.active)*@
                @*@Html.ActionLink("Monto", "Edit", "checks", new { uniquefield = ViewBag.checkUF, search = ViewBag.CurrentSearch, sort = ViewBag.activeSort }, null)*@
                <a class="refreshPartialMov" href="/checkDetails/Index?checkId=@Html.Raw(ViewBag.checkId + "&search=" + ViewBag.CurrentSearch + "&page=" + ViewBag.page + "&sort=" + ViewBag.activeSort)">Active</a>
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr class="@Html.Raw("showData" + item.id + (item.active == true ? String.Empty : " danger"))" >

                <td class="checkNumberItem">
                    @*@Html.DisplayFor(modelItem => item.checks.checkNumber)*@
                </td>
                <td class="nameItem">
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td class="amountItem">
                    @Html.DisplayFor(modelItem => item.amount)
                </td>
                <td class="activeItem">
                    @Html.DisplayFor(modelItem => item.active)
                </td>
                <td class="buttonsCell">
                    @*@Html.ActionLink("Edit", "Edit", "checkDetails", new { id = item.id }, new { @class = "btnEdit btn btn-primary btn-xs", @id = "edit" + item.id})*@
                    @*<a id="@Html.Raw("edit" + item.id)" class="btnEdit btn btn-primary btn-xs" href="/checkDetails/getMovement?id=@Html.Raw(item.id)">Editar</a>*@
                    <a id="@Html.Raw(item.id)" class="btnEdit btn btn-primary btn-xs" href="/checkDetails/Edit?id=@Html.Raw(item.id + "&search=" + ViewBag.CurrentSearch + "&page=" + ViewBag.page + "&sort=" + ViewBag.CurrentSort)" table-id="movements">Editar</a>
                    @*@Html.ActionLink("Details", "Details", new { id = item.id }, new { @class = "btn btn-info btn-xs" })*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "btnModalUrl btn btn-danger btn-xs" })
                </td>
            </tr>
            @*<tr id="@Html.Raw("edit" + item.id)">
                    <td class="checkNumberEdit">
                        <input type="text" readonly/>
                    </td>
                    <td class="nameEdit">
                        <input type="text" />
                    </td>
                    <td class="amountEdit">
                        <input type="text" />
                    </td>
                    <td class="activeEdit">
                        <input type="checkbox" />
                    </td>
                    <td>
                        <a class="btn btn-primary btn-sm">Guardar</a>
                        <a class="btn btn-default btn-sm">Cancelar</a>
                    </td>
                </tr>*@
        }
    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", "checkDetails", new { ViewBag.checkId, search = ViewBag.CurrentSearch, page, sort = ViewBag.CurrentSort }))